"""Generated cover letter content model."""

from pydantic import BaseModel, Field


class CoverLetter(BaseModel):
    """Structured cover letter generated by the LLM (Stage 1 output)."""

    company: str
    role_title: str
    salutation: str = Field(
        description="Opening salutation (e.g., 'Dear Hiring Manager,')"
    )
    opening_paragraph: str = Field(description="Hook: why this role, why this company")
    body_paragraphs: list[str] = Field(
        description="2-3 paragraphs connecting experience to role requirements"
    )
    closing_paragraph: str = Field(description="Call to action and sign-off lead-in")
    sign_off: str = Field(
        default="Sincerely,",
        description="Formal closing (e.g., 'Sincerely,' 'Best regards,')",
    )
    candidate_name: str
    tone_notes: str | None = Field(
        default=None,
        description="Brief explanation of tone choices made",
    )
